apiVersion: v1
kind: Service
metadata:
  name: NexisClaw
  labels:
    app: NexisClaw
spec:
  type: ClusterIP
  selector:
    app: NexisClaw
  ports:
    - name: gateway
      port: 18789
      targetPort: 18789
      protocol: TCP
