#!/usr/bin/env bash
set -euo pipefail

ROOT_DIR="$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)"
source "$ROOT_DIR/scripts/lib/docker-build.sh"
IMAGE_NAME="${NEXISCLAW_INSTALL_E2E_IMAGE:-NexisClaw-install-e2e:local}"
INSTALL_URL="${NEXISCLAW_INSTALL_URL:-https://NexisClaw.bot/install.sh}"

OPENAI_API_KEY="${OPENAI_API_KEY:-}"
ANTHROPIC_API_KEY="${ANTHROPIC_API_KEY:-}"
ANTHROPIC_API_TOKEN="${ANTHROPIC_API_TOKEN:-}"
NEXISCLAW_E2E_MODELS="${NEXISCLAW_E2E_MODELS:-}"

echo "==> Build image: $IMAGE_NAME"
docker_build_run install-e2e-build \
  -t "$IMAGE_NAME" \
  -f "$ROOT_DIR/scripts/docker/install-sh-e2e/Dockerfile" \
  "$ROOT_DIR/scripts/docker"

echo "==> Run E2E installer test"
docker run --rm \
  -e NEXISCLAW_INSTALL_URL="$INSTALL_URL" \
  -e NEXISCLAW_INSTALL_TAG="${NEXISCLAW_INSTALL_TAG:-latest}" \
  -e NEXISCLAW_E2E_MODELS="$NEXISCLAW_E2E_MODELS" \
  -e NEXISCLAW_INSTALL_E2E_OPENAI_MODEL="${NEXISCLAW_INSTALL_E2E_OPENAI_MODEL:-}" \
  -e NEXISCLAW_INSTALL_E2E_OPENAI_PROVIDER_TIMEOUT_SECONDS="${NEXISCLAW_INSTALL_E2E_OPENAI_PROVIDER_TIMEOUT_SECONDS:-}" \
  -e NEXISCLAW_INSTALL_E2E_PREVIOUS="${NEXISCLAW_INSTALL_E2E_PREVIOUS:-}" \
  -e NEXISCLAW_INSTALL_E2E_SKIP_PREVIOUS="${NEXISCLAW_INSTALL_E2E_SKIP_PREVIOUS:-0}" \
  -e NEXISCLAW_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS="${NEXISCLAW_INSTALL_E2E_AGENT_TURN_TIMEOUT_SECONDS:-300}" \
  -e NEXISCLAW_INSTALL_E2E_AGENT_TURNS_PARALLEL="${NEXISCLAW_INSTALL_E2E_AGENT_TURNS_PARALLEL:-1}" \
  -e NEXISCLAW_INSTALL_E2E_AGENT_TOOL_SMOKE="${NEXISCLAW_INSTALL_E2E_AGENT_TOOL_SMOKE:-1}" \
  -e NEXISCLAW_NO_ONBOARD=1 \
  -e OPENAI_API_KEY \
  -e ANTHROPIC_API_KEY \
  -e ANTHROPIC_API_TOKEN \
  "$IMAGE_NAME"
