export const browserCoreExamples = [
  "NexisClaw browser status",
  "NexisClaw browser start",
  "NexisClaw browser start --headless",
  "NexisClaw browser stop",
  "NexisClaw browser tabs",
  "NexisClaw browser open https://example.com",
  "NexisClaw browser focus abcd1234",
  "NexisClaw browser close abcd1234",
  "NexisClaw browser screenshot",
  "NexisClaw browser screenshot --full-page",
  "NexisClaw browser screenshot --ref 12",
  "NexisClaw browser snapshot",
  "NexisClaw browser snapshot --format aria --limit 200",
  "NexisClaw browser snapshot --efficient",
  "NexisClaw browser snapshot --labels",
];

export const browserActionExamples = [
  "NexisClaw browser navigate https://example.com",
  "NexisClaw browser resize 1280 720",
  "NexisClaw browser click 12 --double",
  "NexisClaw browser click-coords 120 340",
  'NexisClaw browser type 23 "hello" --submit',
  "NexisClaw browser press Enter",
  "NexisClaw browser hover 44",
  "NexisClaw browser drag 10 11",
  "NexisClaw browser select 9 OptionA OptionB",
  "NexisClaw browser upload /tmp/NexisClaw/uploads/file.pdf",
  'NexisClaw browser fill --fields \'[{"ref":"1","value":"Ada"}]\'',
  "NexisClaw browser dialog --accept",
  'NexisClaw browser wait --text "Done"',
  "NexisClaw browser evaluate --fn '(el) => el.textContent' --ref 7",
  "NexisClaw browser console --level error",
  "NexisClaw browser pdf",
];
